### ISSUE TITLE
CRYPTO_malloc@@OPENSSL_1.0.0

### ISSUE THREAD

**Issue by levin-kelevra** [P0cL4bs/Kadimus#1]
Ubuntu 14.04.2 x86_64

$ make
gcc -Wall -Wextra -O3 -g   -c -o src/kadimus_common.o src/kadimus_common.c
src/kadimus_common.c: В функции «hex_print»:
src/kadimus_common.c:17:3: предупреждение: format «%d» expects argument of type «int», but argument 3 has type «size_t» [-Wformat]
src/kadimus_common.c:17:3: предупреждение: format «%d» expects argument of type «int», but argument 3 has type «size_t» [-Wformat]
src/kadimus_common.c:29:3: предупреждение: field width specifier «*» expects argument of type «int», but argument 3 has type «size_t» [-Wformat]
src/kadimus_common.c:29:3: предупреждение: field width specifier «*» expects argument of type «int», but argument 3 has type «size_t» [-Wformat]
gcc -Wall -Wextra -O3 -g   -c -o src/kadimus_mem.o src/kadimus_mem.c
gcc -Wall -Wextra -O3 -g   -c -o src/kadimus_request.o src/kadimus_request.c
gcc -Wall -Wextra -O3 -g   -c -o src/kadimus_str.o src/kadimus_str.c
gcc -Wall -Wextra -O3 -g   -c -o src/kadimus_xpl.o src/kadimus_xpl.c
gcc -Wall -Wextra -O3 -g   -c -o src/kadimus_regex.o src/kadimus_regex.c
gcc -Wall -Wextra -O3 -g   -c -o src/kadimus_socket.o src/kadimus_socket.c
src/kadimus_socket.c: В функции «bind_shell»:
src/kadimus_socket.c:192:9: предупреждение: ignoring return value of «write», declared with attribute warn_unused_result [-Wunused-result]
src/kadimus_socket.c:201:9: предупреждение: ignoring return value of «write», declared with attribute warn_unused_result [-Wunused-result]
src/kadimus_socket.c: В функции «reverse_shell»:
src/kadimus_socket.c:103:9: предупреждение: ignoring return value of «write», declared with attribute warn_unused_result [-Wunused-result]
src/kadimus_socket.c:112:9: предупреждение: ignoring return value of «write», declared with attribute warn_unused_result [-Wunused-result]
gcc -Wall -Wextra -O3 -g   -c -o src/kadimus_io.o src/kadimus_io.c
/usr/bin/ld: src/kadimus_request.o: неопределённая ссылка на символ «CRYPTO_malloc@@OPENSSL_1.0.0»
//lib/x86_64-linux-gnu/libcrypto.so.1.0.0: error adding symbols: DSO missing from command line
collect2: выполнение ld завершилось с кодом возврата 1
make: *** [kadimus] Ошибка 1

**Comment by mmxxm** [comment]
Do you have openssl library installed ?
Try the command:

```sudo apt-get install libssl-dev```

**Comment by levin-kelevra** [comment]
Sure,
libssl-dev:
  Установлен: 1.0.1f-1ubuntu2.11
  Кандидат:   1.0.1f-1ubuntu2.11
  Таблица версий:
 *** 1.0.1f-1ubuntu2.11 0
        500 http://ru.archive.ubuntu.com/ubuntu/ trusty-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu/ trusty-security/main amd64 Packages
        100 /var/lib/dpkg/status
     1.0.1f-1ubuntu2 0
        500 http://ru.archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages

**Comment by mmxxm** [comment]
```sudo ln -s /lib/x86_64-linux-gnu/libcrypto.so.* /lib/x86_64-linux-gnu/libcrypto.so.1.0.0```

**Comment by levin-kelevra** [comment]
$ ll /lib/x86_64-linux-gnu/libcrypto.so*
-rw-r--r-- 1 root root 1641288 июля   2  2014 /lib/x86_64-linux-gnu/libcrypto.so.0.9.8
-rw-r--r-- 1 root root 1930528 марта 19 18:16 /lib/x86_64-linux-gnu/libcrypto.so.1.0.0

i.e. file /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 allready exist

**Comment by mmxxm** [comment]
I did a little modification in the Makefile: https://github.com/P0cL4bs/Kadimus/commit/f463729a465d32ee0365863dafbd605986d8696e.
You can do it 
```
make
```
To test if works.

**Comment by levin-kelevra** [comment]
$ rm -f src/*.o
$ make
gcc -Wall -Wextra -O3 -g   -c -o src/kadimus_common.o src/kadimus_common.c
src/kadimus_common.c: В функции «hex_print»:
src/kadimus_common.c:17:3: предупреждение: format «%d» expects argument of type «int», but argument 3 has type «size_t» [-Wformat]
src/kadimus_common.c:17:3: предупреждение: format «%d» expects argument of type «int», but argument 3 has type «size_t» [-Wformat]
src/kadimus_common.c:29:3: предупреждение: field width specifier «*» expects argument of type «int», but argument 3 has type «size_t» [-Wformat]
src/kadimus_common.c:29:3: предупреждение: field width specifier «*» expects argument of type «int», but argument 3 has type «size_t» [-Wformat]
gcc -Wall -Wextra -O3 -g   -c -o src/kadimus_mem.o src/kadimus_mem.c
gcc -Wall -Wextra -O3 -g   -c -o src/kadimus_request.o src/kadimus_request.c
gcc -Wall -Wextra -O3 -g   -c -o src/kadimus_str.o src/kadimus_str.c
gcc -Wall -Wextra -O3 -g   -c -o src/kadimus_xpl.o src/kadimus_xpl.c
gcc -Wall -Wextra -O3 -g   -c -o src/kadimus_regex.o src/kadimus_regex.c
gcc -Wall -Wextra -O3 -g   -c -o src/kadimus_socket.o src/kadimus_socket.c
src/kadimus_socket.c: В функции «bind_shell»:
src/kadimus_socket.c:192:9: предупреждение: ignoring return value of «write», declared with attribute warn_unused_result [-Wunused-result]
src/kadimus_socket.c:201:9: предупреждение: ignoring return value of «write», declared with attribute warn_unused_result [-Wunused-result]
src/kadimus_socket.c: В функции «reverse_shell»:
src/kadimus_socket.c:103:9: предупреждение: ignoring return value of «write», declared with attribute warn_unused_result [-Wunused-result]
src/kadimus_socket.c:112:9: предупреждение: ignoring return value of «write», declared with attribute warn_unused_result [-Wunused-result]
gcc -Wall -Wextra -O3 -g   -c -o src/kadimus_io.o src/kadimus_io.c
/usr/bin/ld: src/kadimus_request.o: неопределённая ссылка на символ «CRYPTO_malloc@@OPENSSL_1.0.0»
//lib/x86_64-linux-gnu/libcrypto.so.1.0.0: error adding symbols: DSO missing from command line
collect2: выполнение ld завершилось с кодом возврата 1
make: *** [kadimus] Ошибка 1

The same ...

**Comment by mmxxm** [comment]
you update the code ?

```
$ git pull
$ make
```

**Comment by mmxxm** [comment]
You can also try reinstall libssl-dev, it can work !

**Comment by levin-kelevra** [comment]
it's work on other laptop with the same packages installed.
