### ISSUE TITLE
proplem when try to install kadimus on kali sana 

### ISSUE THREAD

**Issue by hcstorm** [P0cL4bs/kadimus#1]
this message  shown when it install it :
~/Kadimus# make
gcc -Wall -Wextra -O3 -c -o bin/kadimus_common.o src/kadimus_common.c
gcc -Wall -Wextra -O3 -c -o bin/kadimus_mem.o src/kadimus_mem.c
gcc -Wall -Wextra -O3 -c -o bin/kadimus_request.o src/kadimus_request.c
In file included from src/kadimus_request.c:1:0:
src/kadimus_request.h:6:28: fatal error: openssl/crypto.h: No such file or directory
 #include <openssl/crypto.h>
                            ^
compilation terminated.
Makefile:21: recipe for target 'bin/kadimus_request.o' failed
make: **\* [bin/kadimus_request.o] Error 1

**Comment by ghost** [comment]
Try install libssl
