### ISSUE TITLE
unknow Error while make command

### ISSUE THREAD

**Issue by nittoworld** [P0cL4bs/kadimus#15]
make
  CC bin/techniques/auth-log-poison.o
src/techniques/auth-log-poison.c:11:10: fatal error: libssh/libssh.h: No such file or directory
   11 | #include <libssh/libssh.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:22: bin/techniques/auth-log-poison.o] Error 1

**Comment by ghost** [comment]
read the README
