### ISSUE TITLE
Configure

### ISSUE THREAD

**Issue by joridos** [P0cL4bs/Kadimus#2]
Sounds good create a configure file, this solves common errors, like issue #1

**Comment by mmxxm** [comment]
Nice ideia, I'll do it ! :+1:

**Comment by joridos** [comment]
:smile:

**Comment by mmxxm** [comment]
Done: https://github.com/P0cL4bs/Kadimus/commit/f2ac6e9f20870c4b2fcfe85b3ba218d5591b920e

**Comment by joridos** [comment]
Cool brother
