### ISSUE TITLE
Example video??

### ISSUE THREAD

**Issue by lgcambero** [P0cL4bs/kadimus#2]
It sounds interesting, some sample video ??

**Comment by ghost** [comment]
hi, I dont have any sample video now, can do it in future, until I or anybody make a video keep this issue open

**Comment by lgcambero** [comment]
I tried "apt-get install libssl-dev"
Any ideas?
![estosi](https://cloud.githubusercontent.com/assets/11602705/16548778/f69e28e8-416c-11e6-826e-2bcc4d94cd6b.png)

**Comment by lgcambero** [comment]
Already solved.

**Comment by iamtutu** [comment]
@lgcambero how did you solve the curl ? thanks

**Comment by chinnidiwakar** [comment]
apt install libcurl4-openssl-dev -y

this will solve curl issue.
