### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by testernoobkali** [P0cL4bs/kadimus#7]
I have ran the configure but it fails to makefile 

oot@kali:~/Downloads/Kadimus# make
gcc -Wall -Wextra -O3 -c -o bin/kadimus_request.o src/kadimus_request.c
In file included from src/kadimus_request.c:1:0:
src/kadimus_request.h:4:23: fatal error: curl/curl.h: No such file or directory
 #include <curl/curl.h>
                       ^
compilation terminated.
Makefile:21: recipe for target 'bin/kadimus_request.o' failed
make: *** [bin/kadimus_request.o] Error 1

**Comment by slayerlab** [comment]
Check if you have libcurl installed in your system.

on kali, try it:
`apt install libcurl-dev`

**Comment by testernoobkali** [comment]
sorry it worked!
